### ISSUE TITLE
Explain better possible read of un-owned memory in is_valid_*_atom

### ISSUE THREAD

**Issue by Licenser** [lemire/simdjson#137]
In the state machine on level 0, if a atom (ture,false,null) is found it copies the source string to a new buffer of at least 32 bytes of size - as far as I understand to ensure that the `is_valid_*_atom` functions won't try to read memory that doesn't belong to us.

This check is skipped for nested atoms, however it seems that they too could run into the situation of reading beyond their space.

Take the json `[null]` for example. In the state machine it would transition to `root`(offset 0)->`array_begin`(offset  1) and here hit the `'n'` case that calls `is_valid_null_atom(buf + 1)`  (pointing to the `n` in `[null]`.

Now `is_valid_null_atom` will do it's thing and as part of that copy 64 bit (8 byte) of data from buf + 1 that would mean `null]___` (`_`denoting unowned memory).

**Comment by lemire** [comment]
@Licenser 

As per the code you point out to, the memcpy is done for the following reason...

```
// we need to make a copy to make sure that the string is NULL terminated.
```
https://github.com/lemire/simdjson/blob/master/src/stage2_build_tape.cpp#L194

I am not sure what you mean by "unowned memory". The code ensures that we can read at least SIMDJSON_PADDING bytes above the advertised length of the buffer (doing a memory reallocation if needed)...

https://github.com/lemire/simdjson/blob/master/src/jsonparser.cpp#L12-L41

What you cannot do is write to this memory (anything beyond the advertised length) ... that would be unsafe... but reading it is fine (we take the necessary precaution).

It is unsafe to write to this memory because we do not know what is written there, if anything. It could be used by any other code in the same process... but we do not care about it because we do not make use of these read bytes... they are ignored.

The reason we need to make a copy in some cases, is that we want to be able to *write*...

**Comment by lemire** [comment]
Note to self: this should be documented more carefully.

**Comment by Licenser** [comment]
Oh, I didn't see the relocation in the JSON parser :) I just stumbled over this with the rust range checking. Thanks for taking the time of explaining why it is safe!

**Comment by lemire** [comment]
I am re-opening this since I think it needs to get documented.

Note that the same 'trick' can work in Rust. In the worst case, you may need to memcpy the input data. But even if you need to do that... the cost of a copy + mem. alloc. is really not that bad. Of course, you increase memory usage which is bad... but computationally, it is not that bad.

**Comment by Licenser** [comment]
👍 I went for "closed as it answered my question" it's easier to re-open then to have a ticket open forever that no one knows when to close :D

**Comment by lemire** [comment]
This is fixed with better comments and static_asserts in a branch about to be merged.
