### ISSUE TITLE
Support parsing newline delimited JSON (ndjson) + streams of JSON documents

### ISSUE THREAD

**Issue by nichtich** [lemire/simdjson#188]
Utility function `get_corpus` reads the entire file which does not work for very large JSON data sets. These data sets are often handled in form of newline delimited JSON (ndjson). An utility function or code example would be nice to loop over lines of a `.ndjson` file and parse each line.  My rusted knowledge of C++ and memory management is not enough to judge whether simply using `getline` is the best approach: the documentation says that `padded_string` class is recommended but `getline` uses `realloc` internally anyway (?)

**Comment by lemire** [comment]
This is intriguing. Very nice issue. I doubt that `getline` is the proper API for us... but it is worth exploring.

**Comment by craiig** [comment]
Hi, just wanted to add to this issue. I'd like to use SIMDJSON for some data processing research, but parsing multi-line json is a requirement. My use case is parsing a stream of JSON records of unknown length (but buffered up to a reasonable size, like 8KB).

One simple solution we have for now is just scanning for a newline before passing the string and the length to the json parser. This is probably not ideal because we're not using SIMD instructions to identify the newline, and I suspect this newline search could be integrated with the parser to save some cycles. 

I suggest a simple API behaviour - accept a char* and a max length, and then parse until a newline is reached, returning the parsed object and pointer to the next character to read. Internally this could be implemented as a SIMD newline scan before the rest of the parser runs, or perhaps integrated with the existing search for structural characters (depending which is deemed faster?).

Thanks for considering!

**Comment by lemire** [comment]
I wrote a blog post to illustrate why going through getline does not make sense in my opinion: [How fast is getline in C++?](https://lemire.me/blog/2019/06/18/how-fast-is-getline-in-c/)

**Comment by lemire** [comment]
@craiig 

Am I correct in thinking that your application involves multiple JSON documents, one per line? Like ndjson. Right?

For something of the sort, you are absolutely correct, in my opinion, that you want support *in* the parser.

**Comment by craiig** [comment]
Yep, that's correct it's the ndjson spec (http://ndjson.org/) . This would be a fantastic improvement and make SIMDJSON very relevant for lots of use cases!

**Comment by lemire** [comment]
Right. Let us make it happen.

**Comment by lemire** [comment]
I have marked this as "help wanted". If anyone is interested in working on this problem, please speak up. I am interested but I may not get to it in the very near future.

**Comment by nichtich** [comment]
[jq](https://stedolan.github.io/jq/) reads concatenated JSON documents optionally separated by whitespace (e.g. two documents "`{"foo":23} {"bar":42}`). Actually we don't need to parse *lines* but

* stop parsing after having read a full valid JSON document (`{"foo":23}`) with a pointer where to proceed, and
* pause parsing when the end of a input is reached with an incomplete JSON document (e.g. `{"`) and allow to proceed with a new input buffer

**Comment by lemire** [comment]
@nichtich For best speeds, you almost surely do not want to parse in small chunks like so. It is going to be very hard to be fast if you process 80 characters at a time.

**Comment by lcdavid94** [comment]
ndjson requires each json document to be in one line. Is it possible to support a more general case where a file includes multiple json documents, and each document can take up multiple lines? Something like:
```
{
"a": 1,
"b": 2
}
{
"a": 5,
"b": 6
}
```

**Comment by nichtich** [comment]
Yes, this use case is a special case of parsing a sequence of optional whitespace delimited JSON documents (like supported by `jq`).

**Comment by lemire** [comment]
@lcdavid94 @nichtich  It is likely more work having to separate out the lines. Implementing the more general model is probably easier and would lead to a faster parser.

**Comment by lemire** [comment]
See https://github.com/lemire/simdjson/issues/147

**Comment by lemire** [comment]
cc @piotte13

**Comment by jplauri** [comment]
FWIW, let me also say that I'd be very interested in the ndjson use case.

**Comment by craiig** [comment]
Nice to see some traffic on this, is work starting on this? I would be happy to give feedback on APIs, do some testing, etc. Let me know.

**Comment by lemire** [comment]
> is work starting on this? I would be happy to give feedback on APIs, do some testing, etc. Let me know.

@piotte13 should start working on this next week?

**Comment by piotte13** [comment]
Hello everyone, 
We got a working prototype that could solve this issue and allow us to support large files (>4GB)! 

### Exemple usage:


```cpp
#include "simdjson/parsedjson.h"
#include "simdjson/jsonstream.h"

simdjson::padded_string string;
simdjson::get_corpus(filename).swap(string);


//simdjson::JsonStream js{string};
//simdjson::JsonStream js{string, 1000000};
//simdjson::JsonStream js{string.data(), string.size()};
simdjson::JsonStream js{string.data(), string.size(), 1000000}; 
//Where 1000000 represents the batch_size in bytes.  
//We load data in batch to speed things up a bit. (default = 1MB)


int parse_res = simdjson::SUCCESS_AND_HAS_MORE;
simdjson::ParsedJson pj;

//We re-use the same ParsedJson as much as possible, to save allocation time.
//This loop will run as long as the file contains valid JSON documents.
while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) {
    parse_res = js.json_parse(pj);
}
```
### Implementation
The current implementation allows us to parse through large documents faster than the "simple" `std::getline()` alternative.  We still have many ideas to make it even faster, but right now it feels like a good starting point.

### What kind of file is supported?
We opted for a more general case where a file could contain multiple JSON documents no matter the format, as long as it is JSON valid. Therefore, we are not limited to ndjson and jsonline. **We support any file that contains multiple valid JSON documents.**

### API
**I would greatly appreciate some feedback.**  From my point of view, it seems simple and easy to use, but i'm not an end user! 

- Does it fill your needs?
- Is it clear, simple and complete enough?
- Suggestions?

@lemire @craiig @jplauri @nichtich 

Cheers

**Comment by craiig** [comment]
Thanks for working on this! Some brief comments below. I wasn't sure where to put them since you sent us a message in a few different places, so I chose the original issue.

The interface for specifying a start pointer and a length looks good and would work for my usage.  Although in my usage I have usually worked with a start and end pointers. It's easy to calculate one from the other, so it is not a big deal.

Specifying the batch_size seems odd, what do you mean by "We load data in batch to speed things up a bit." If a pointer is being provided, the data is already in memory, right? This sounds like you might be introducing an internal copy for some reason?

"could contain multiple JSON documents no matter the format, as long as it is JSON valid."
It might be good to define this more concretely. For instance, are you saying that JSON documents can be separated by arbitrary bytes or just \n? How many bytes?

Thanks again.

**Comment by lcdavid94** [comment]
Hi Jeremie,

Thanks for your work!
When constructing the JsonStream, the entire string needs to be passed in. Seems like it is parsing the data 1MB every time anyways, would it be possible to allow the user to pass in 1MB of data every time and ask the user for more when more characters are needed?

Thanks!

**Comment by lemire** [comment]
@craiig 

> Specifying the batch_size seems odd, what do you mean by "We load data in batch to speed things up a bit." If a pointer is being provided, the data is already in memory, right? This sounds like you might be introducing an internal copy for some reason?



This is maybe not clearly explained. 

We don't want to allocate memory dynamically, for performance reasons. So we want to allocate enough memory to comfortably fit any one JSON document (and then we never allocate/deallocate).

This is currently set by the batch size. 

Furthermore, we have a two pass system (stage 1 and stage 2) and the stage 1 just scans everything. Currently, we scan an entire batch once, and then we build the DOM trees one by one in stage 2. Some of the work done in stage 1 is wasted at the end of the batch because we throw it away.

So if you set the batch size very small (but still larger than your largest JSON), you may hit a scenario where the performance is a bit suboptimal due to the waste in stage 1.

Anyhow, in practice, any batch size significantly larger than the largest JSON will do... but if you make it too large, you start to see (almost linearly) a performance decrease (probably due to memory accesses).

So you want a large, but not too large batch size.

With @piotte13, we think that this could be automatically handled, in the sense that you could have a sensible default and then have the system automatically adjust for optimal performance.

Does it answer this particular question of yours?

**Comment by craiig** [comment]
Yep, sounds great. Thanks! Everything looks good to me

**Comment by nichtich** [comment]
~~~c
while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) {
    parse_res = js.json_parse(pj);
}
~~~

* What's the difference between `parse_res == simdjson::SUCCESS_AND_HAS_MORE` in contrast to the current `parse_res != 0`?
* Is it possible to detect whether the parsed string ends or whether it contains non-parseable data at the end? (e.g. `"{}"` vs `"{} content-after-json"`)?
* can we get the line number of the current document?

**Comment by piotte13** [comment]
@craiig 
> "could contain multiple JSON documents no matter the format, as long as it is JSON valid."
> It might be good to define this more concretely. For instance, are you saying that JSON documents can be separated by arbitrary bytes or just \n? How many bytes?
> 
Right.  I thought it was self-explanatory, but I agree it's better to be more precise. 
Any byte that is considered a **whitespace** by the JSON spec will do.  Namely: **space, linefeed, carriage return, horizontal tab.**  Anything that is not whitespace will be parsed as a JSON document and could lead to failure.

Thanks!

**Comment by piotte13** [comment]
@lcdavid94 
> When constructing the JsonStream, the entire string needs to be passed in. Seems like it is parsing the data 1MB every time anyways, would it be possible to allow the user to pass in 1MB of data every time and ask the user for more when more characters are needed?

I can see 2 approaches that could solve this issue.

1. Using **Memory Mapping**. The current API only requires a pointer to the start of your buffer plus its length.  To make it simple, I loaded all the file in an `std::string,` but as you said, it's not very efficient.  What you could do is use Memory Mapping to get a pointer to the start of the buffer and then let the OS load the file dynamically. Quick exemple using [this](https://create.stephan-brumme.com/portable-memory-mapping/) portable Memory Mapping library: 
```cpp
// open file 
MemoryMapped data("myfile.txt"); 
//Get the buffer pointer
const char* buf = (const char*) data.getData();

simdjson::JsonStream js{buf, data.size()};

...
```

2. Give the JsonStream a **new buffer at runtime**.  We could add to the API the option to give a new buffer to the JsonStream without creating a new object. Ex:
 ```cpp
ParsedJson pj;
JsonStream js{buf, buf_size};

js.json_parse(pj);
...

js.set_new_buffer(new_buf, new_buf_size);
js.json_parse();

...
```



Thank you!

**Comment by piotte13** [comment]
@nichtich 

>  What's the difference between `parse_res == simdjson::SUCCESS_AND_HAS_MORE` in contrast to the current `parse_res != 0`?

`simdjson::SUCCESS_AND_HAS_MORE` means the streamer successfully parsed the next JSON document and sees more data in the buffer. **There is potentially more stuff to be parsed**.
`simdjson::SUCCESS` Aka. `0` means the streamer has successfully parsed the next JSON document and is done with the current buffer.  **There is nothing more to be parsed**.

>   Is it possible to detect whether the parsed string ends or whether it contains non-parseable data at the end? (e.g. `"{}"` vs `"{} content-after-json"`)?
> 
If your parsing loop does not end with a `simdjson::SUCCESS`, it means something went wrong with the last chunk of data it tried to parse.  In your case, probably because the content after the last valid JSON document was not valid JSON.  But, remember: `true`, `45`, `"string"`, `null` are all valid documents on their own.

>  can we get the line number of the current document?

Does something like this fill your needs?
```cpp
auto count = 0; //Nb of parsed documents
while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) {
    parse_res = js.json_parse(pj);
    count++; 
}
```



Thanks!

**Comment by nichtich** [comment]
Thanks! Getting document number should be enough for parsing valid ndjson. Getting exact line (and column) number based on occurrences of linefeed and carriage return would be another issue, useful to point to error locations.

**Comment by lcdavid94** [comment]
Thanks!
I have a use case where I need to parse a remote file. I am able to specify which part of the file to load into memory. Therefore, your approach 2 (an API to add new buffer) makes a lot of sense to me.
For your original API and approach 1, I will have to download the file to the local disk, which is something I'd like to avoid.

**Comment by piotte13** [comment]
@lcdavid94 
Good point.  Consider it done.

**Comment by piotte13** [comment]
#364
