### ISSUE TITLE
floating-point parsing with accuracy beyond 1 ULP

### ISSUE THREAD

**Issue by michaeleisel** [lemire/simdjson#242]
it says that the maximum error is 1 ulp for floating-point parsing. it could be further reduced to 0.5 ulp, right? short of that, it would be good to at least understand in which situations this error occurs. for example, i hope it wouldn't occur for numbers like `1.0`.

**Comment by lemire** [comment]
Marked as "help wanted". Pull requests and further analysis are invited.

**Comment by lemire** [comment]
The ULP between two parsed floating-point numbers is an integer... it can be 0,1... It cannot be 0.5.

**Comment by lemire** [comment]
Practically speaking, an ULP of 1 means 15 digits of accuracy because 1/(2**53)~ 1.1e-16.

Very few applications need more than 15 digits of accuracy. It is akin to trying to track the position of molecules on Earth using latitude and longitude.

![image](https://user-images.githubusercontent.com/391987/62259609-e9e84080-b3dc-11e9-8d99-ca4f298ae2a3.png)

**Comment by michaeleisel** [comment]
the ulp is an integer, but the error can be 0.5 (or some other non-integer number) because it's going from decimal to binary, right? my concern for this is around two things:
- logic errors from short numbers like `1.0` used in comparisons in client code (e.g. why you wouldn't use a float in a counter. but i don't know in what cases >0.5 ulp error occurs.
- being a true drop-in replacement for existing json parsers, without any caveats

**Comment by lemire** [comment]
> because it's going from decimal to binary, right?

We don't measure the 'true' value. We compare against a standard float parser. Either we get an identical result, or we differ in the last bit.

New code to compute the actual ULP, using high precision arithmetic is invited. Please contribute.

> logic errors from short numbers like 1.0 used in comparisons in client code

Is this an hypothetical issue (e.g., 1.0 does not get parse correctly) or are you referring to actual issue you can demonstrate with code? I would certainly consider that incorrect integer parsing (even if they have a ".0" suffix) to be a bug.

> being a true drop-in replacement for existing json parsers, without any caveats

RapidJSON has an ULP of one as per our metric unless you turn on high precision float parsing, which is deactivated by default (because it is slow).

It would be very interesting to investigate whether it is possible to achieve a perfect ULP at high speed. 

Have you tried to implement something in this direction? What is your experience so far?

**Comment by plokhotnyuk** [comment]
@michaeleisel I bet that you are arguing for the turn-around conversion of binary representation through textual without lost of any bit.
 
It can be crucial for use cases when processing logic accepts only a range of float point values and users pass an edge value (like minimum bet or fee).

Many parsers provide a couple of functions: 1st is loosing but fast and 2nd which parses with most possible precision and rounding of which is synced with a paired serializing function (usually it is a banking rounding to the nearest even value).

[Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/2e02b3a843896cb7563d4be22d1125fdf7660abd/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1260-L1300) is a simplified version of the 'Moderate Path' algorithm from the awesome library of Alexander Huszagh. It handles ~95% of arbitrary numbers in a base-10 string representation or ~99.8% of those which were serialized from 64-bit binary representation.

**Comment by lemire** [comment]
@plokhotnyuk 

Great link.

Code contributions invited.

**Comment by michaeleisel** [comment]
I will take a look at this within the next couple months. I think we can at least provide the slower, more accurate option for those who want it.

**Comment by lemire** [comment]
@michaeleisel 

Thanks. 

Note that providing the more accurate version is *trivial* in the sense that you can just substitute the final steps of the number parsing by a call to the standard library... What is genuinely hard is to do the accurate parsing *quickly* so that you can still run at gigabytes per second.

In other words, we go fast with just up to one bit out of 64 of error... going without even bit of error, but going 10x slower is not good. **That is, there is no point in using simdjson if the parsing is going to be slow.**

**Comment by michaeleisel** [comment]
i disagree, there are lots of value adds in this library besides faster floating-point parsing. furthermore, most json payloads in my experience have very few floats. but it would be nice for it to be fast.

**Comment by michaeleisel** [comment]
a few things:
- correct me if i'm wrong, but it looks like when processing each digit past the decimal point, we are accumulating an error (admittedly in a long double), by incorporating a power of ten, which of course is never perfectly accurate. how are we sure that the maximum error here is even capped at 1 ULP? why not form as many numbers as possible into an integer before doing a multiplication? for example, convert 17-18 numbers past the decimal point into a uint64 (corresponding to the 64 bit mantissa of an 80-bit long double), then multiply that by a power of ten, then we can take advantage of http://www.exploringbinary.com/fast-path-decimal-to-floating-point-conversion/
- what if we parse the integer component before the decimal as its own double, then parse the decimal component afterwards as a separate double, and then add them together. this takes advantage of the fact that integers can be represented with perfect accuracy (or in cases that they're not, where they're too big, they won't be affected by the decimal component). this, combined with the strategy from the first point, would mean that simdjson gets perfect precision in more cases, such as all the doubles in canada.json
- strategies like this one also make it clear when the float parser is not necessarily perfect, and so at that point it's easy to either return the double as-is or take a slow path (e.g. if the user has opted in with a config setting to use a slow path)

the details will of course be different if `long double` is only 64 bits (does that happen anywhere in practice?), but still the same principle

**Comment by michaeleisel** [comment]
another alternative approach is to cache the mantissa for each decimal place, i.e.:
```
uint64_t mantissa(int i, int pow) {...}

{{mantissa(1, 1), mantissa(2, 1), ...}, {mantissa(1, 2), ...}}
```
and then you add up all the mantissas. with a bit of trickery, you can lower the odds that this will force the slow path to, e.g., 17/2^55. however, i wasn't able to get it as fast as strategies like the one mentioned. would it be that the fetch from the lookup table is slower than a multiplication, even when it's in the L1 cache? i also didn't mess around with vectorization, which i imagine you could use here (e.g. doing a gather to do multiple lookups at once)

**Comment by lemire** [comment]
@michaeleisel I think you are focusing on `parse_float` but this function is almost never called.

I am sure that `parse_float` can be entirely redone better, for both better performance and more accuracy. If you want to take a stab at it... please do!!!

But even if `parse_float` were perfect, this should impact number parsing only in the special cases where you have lots of digits. This does not *never* happen, some files rely on `parse_float` but the overwhelming majority of our numbers are parsed in the `parse_number` and that's where the true challenge lies!!!

**Comment by lemire** [comment]
> what if we parse the integer component before the decimal as its own double, then parse the decimal component afterwards as a separate double, and then add them together. this takes advantage of the fact that integers can be represented with perfect accuracy (or in cases that they're not, where they're too big, they won't be affected by the decimal component).

We already use the integer representation in `parse_number`. But I think you are in the `parse_float` function which handles the scenario where we have lots of digits.

When you have lots of digits, all sorts of things can happen... If you have something like...

31323321321321321321321321321321421321321321321321.31323321321321321321321321321321421321321321321321

nothing can be represented as an integer, not the integer portion, not the decimal portion. You have overflow all over.

**Comment by lemire** [comment]
> why not form as many numbers as possible into an integer before doing a multiplication

This is what we do in `parse_number`.

**Comment by michaeleisel** [comment]
yes, good point, i was focusing just on that function. however, i do think a few things are still true:
- parsing the decimal component as a separate double will give perfect accuracy for more cases
- the cached mantissa approach can be vectorized, so unless lookups are just way more expensive than arithmetic (curious to know your thoughts on that), that could be the way to go

**Comment by lemire** [comment]
> parsing the decimal component as a separate double will give perfect accuracy for more cases

Have you tried it out?

> the cached mantissa approach can be vectorized, so unless lookups are just way more expensive than arithmetic (curious to know your thoughts on that), that could be the way to go

Do you have code we could look at?

We already vectorized the computation of the mantissa in `parse_number`.

**Comment by michaeleisel** [comment]
what vectorization are you referring to? just `parse_eight_digits_unrolled`, or anything else? here is a non-vectorized version of what i'm talking about: https://github.com/michaeleisel/strtod/blob/master/macFtoA/main.c#L218 . i don't see anything like it in `parse_number`. there are many variations, e.g. keeping a 128-bit mantissa, or using multiple lookup tables, each with a different shift amount, which allows you to just add without any shifting. the key thing is that, while it's not perfectly accurate, it's easy to find an upper bound for it so you know if you need to fall back. in my benchmarks it wasn't as fast as rapidjson's, so i guess there is more work to be done.

this is also interesting: https://www.reddit.com/r/rust/comments/a6j5j1/making_rust_float_parsing_fast_and_correct/

**Comment by michaeleisel** [comment]
s/upper bound/upper bound for the error

**Comment by michaeleisel** [comment]
and as for trying out parsing the decimal component separately, there is no need to try it out to show correctness for more cases, the math is straightforward based upon https://www.exploringbinary.com/fast-path-decimal-to-floating-point-conversion/

**Comment by lemire** [comment]
@michaeleisel 

> what vectorization are you referring to? just parse_eight_digits_unrolled

Yes, that.

**Comment by lemire** [comment]
>  the math is straightforward based upon

I do not see much mathematics in this reference you offer.

Here is what I think it is claiming. If 0 ≤ s ≤ 2^53 and if  10^0 ≤ p ≤ 10^22 then

1. Both s and p can be represented exactly as 64-bit floating-point values (binary64). I think this is true and can be demonstrated by factoring 10.

2. Because s and p can be represented exactly as floating-point values, then s * p and s / p will produce correctly rounded values.

Where is the demonstration of this last step? Shouldn't it imply, for example, that `2641/1000000 == 2.641e-9` is true (it is not in general).

Surely node (powered by the V8 javascript engine) should serve as a reference... let us see what it has to say...

<img width="235" alt="Screen Shot 2019-08-14 at 10 42 36 PM" src="https://user-images.githubusercontent.com/391987/63069438-d365dd00-bee4-11e9-8623-e97a01a88919.png">

<img width="218" alt="Screen Shot 2019-08-14 at 10 45 30 PM" src="https://user-images.githubusercontent.com/391987/63069535-3c4d5500-bee5-11e9-9dff-625198eeac28.png">

So it is not a simple matter of decomposing the problem into values that you can perfectly represent as doubles and then just doing arithmetic over doubles.

I am sure you can reason these things out, but anyone who does so should have  code to back up the analysis that we can test.

**Comment by michaeleisel** [comment]
I see, I was referring to the math being clear for why computing a double for the integer and decimal separately being good follows from the article. But as for the article itself... "This process relies implicitly on... that IEEE multiplication and division produce correctly rounded results". I've always believed that this is true, are you saying it's not? But most importantly, this is how RapidJSON does their full-precision float parsing, see line 231 of http://rapidjson.org/strtod_8h_source.html . As for what's going on with V8, I don't know enough. Perhaps one issue is that it's trying to use 1e-9 as a double.

**Comment by lemire** [comment]
I don’t know what RapidJSON does, but as you can see, no, processors do not necessarily round perfectly ... often  the ULP is within one of the right value.

**Comment by michaeleisel** [comment]
I would be much more curious to see an example in C, or better yet, assembly. Like I said, there may be weirdness around 1e-9 etc.. As for RapidJSON, it's probably the most battle-tested JSON library out there, and it's by Amazon among others. I would be very surprised if it wasn't correct. In general, everything I've read states that processors/compilers do round correctly. For example, in https://gcc.gnu.org/wiki/FloatingPointMath , gcc indicates that it is indeed compliant as long as you're not using flags like -ffast-math. It states, "This option (ffast-math) is not turned on by any -O option besides -Ofast since it can result in incorrect output for programs that depend on an exact implementation of IEEE or ISO rules/specifications for math functions" https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html . Note that this is leaving aside rounding modes and just assuming we're using round to nearest.

**Comment by lemire** [comment]
I never stated that RapidJSON was incorrect, I wrote that I do not know what it does. I expect it is correct.

**Comment by lemire** [comment]
@michaeleisel I think you are correct. We can parse almost all our examples except maybe canada.json with perfect rounding without atrocious performance.

**Comment by michaeleisel** [comment]
yes, and canada.json too if we split up the int and decimal components. we can also get tricky with 80-bit long doubles if we want

**Comment by lemire** [comment]
> yes, and canada.json too if we split up the int and decimal components

Maybe.

**Comment by lemire** [comment]
@michaeleisel 

Splitting does not really help because while `30276465416/100000000000 == 0.30276465416`, it is not true that `2 + 30276465416/100000000000 == 2.30276465416`.

**Comment by lemire** [comment]
I have a PR with perfect number parsing over all example files, except canada.json. https://github.com/lemire/simdjson/pull/281

The canada.json has many numbers like `83.113876000000118`. Sadly, we have that `83113876000000118>(1<<53)` so we can't just parse the integer `83113876000000118` and then multiply by `10^-15` because  `83113876000000118`  is too large.

Note that this is precisely the scenario mocked above... The canada.json file has geographic data points at the precision of individual atoms.

**Comment by michaeleisel** [comment]
i am optimistic we can find a way, at least for a lot of the values. here are a few thoughts:
- we can determine when a value like `2.30276465416` is at that dangerous boundary. i am still working out the math, but it's something like, when the part that is removed from the decimal component is either `10...0` or `1...1`. then we can fall back to the slow path. i believe there are some flags that get set after the multiplication as well that will reduce the number of slow path cases
- on x86-64 (but sadly not arm), long doubles are 80 bits, and it will make things easy, although i don't know if there's a perf hit, but it could just be when a normal double isn't enough

**Comment by michaeleisel** [comment]
rounding modes seemed interesting, but from what i've read changing the rounding mode can be slow, and since it's global state, it's not good to do for a library

**Comment by michaeleisel** [comment]
another separate optimization: we could "enqueue" doubles to be computed and then do them all at once with a vector instruction like `divpd`

**Comment by michaeleisel** [comment]
s/computed/divided

**Comment by lemire** [comment]
Work is being done in the following PR: https://github.com/lemire/simdjson/pull/333

**Comment by lemire** [comment]
See https://github.com/minio/minio/pull/8401

**Comment by lemire** [comment]
Moved to release 0.4, this will not be part of release 0.3 as we have more critical design issues.

**Comment by michaeleisel** [comment]
🍾
