### ISSUE TITLE
MSVC 2019 was generating AVX-512 instruction in AVX/AVX2 mode 

### ISSUE THREAD

**Issue by DBJDBJ** [lemire/simdjson#475]
#### [fixed in: visual studio 2019 version 16.4.4](https://developercommunity.visualstudio.com/content/problem/848627/msvc2019-generates-avx-512-instruction-in-avxavx2.html)

If it matters ....

**Comment by lemire** [comment]
Do you think we build simdjson with the /AVX flag? My expectation is that we do not.

**Comment by DBJDBJ** [comment]
> If it matters ....

I said above, besides that SIMD is "not my cup of tea"

**Comment by lemire** [comment]
So I will assume that we do not use these flags. I think if we did, it would be a bug.

Note: it might be worth it to document that they should not be used!

**Comment by DBJDBJ** [comment]
> Note: it might be worth it to document that they should not be used!

what happens if simdjson headers are included in an msvc built app, that uses the /AVX flag?

**Comment by lemire** [comment]
@DBJDBJ 

I expect that it will break runtime dispatch. That is, the parser will work on a recent processor, but it will fail on a pre-AVX processor. This is unavoidable if it happens from our end because once you have specified the command line /AVX, the compiler is given the right to use AVX instructions whenever it likes.

Yet, my expectation is also that the code should still work (on recent processors).

**Comment by DBJDBJ** [comment]
It seems to me a little compilation guide might be in order @lemire ? especially to users using simdjson in their SIMD programs on nobody knows what CPU's...

**Comment by lemire** [comment]
> It seems to me a little compilation guide might be in order @lemire ? especially to users using simdjson in their SIMD programs on nobody knows what CPU's...


There are many things that @lemire ought to be doing, but he still only has 24 hours per day.
