### ISSUE TITLE
Better errors in the high-level interface.

### ISSUE THREAD

**Issue by TkTech** [lemire/simdjson#55]
The high-level interface (such as `json_parse`) only return `True` or `False`, but can fail under numerous different conditions.

As someone building on top of simdjson, I either need to hijack `stderr` when calling these methods and search the string to figure out what really went wrong, or I need to re-implement them entirely.

It would be preferable to instead return an error code, using 1 for success and negative values for the various errors.

**Comment by lemire** [comment]
This is entirely legitimate.

**Comment by atomheartother** [comment]
There's a backwards-compatibility problem with doing this the standard way (0 for success, error code otherwise), because as of right now we return `true` on success, which most definitely doesn't evaluate as 0.

@lemire I'm working on a PR for this, but how do you feel about that, returning 0 most definitely will break backwards-compatibility, but it is the standard way to do it so to speak.

**Comment by plokhotnyuk** [comment]
Is it possible to return the error code with an offset where it occurs?

**Comment by TkTech** [comment]
I have no say in this, but IMO the project is so young, now is the time to make these kinds of changes with minimal pain.

**Comment by lemire** [comment]
@atomheartother We can break backward compatibility if we have good reasons to do so.

**Comment by atomheartother** [comment]
The WIP branch to check the progress on this is #82 .

**Comment by lemire** [comment]
We have specific error codes and more have been added in this PR
https://github.com/lemire/simdjson/pull/176

Furthermore we could easily (as is now documented in the code) report on exactly where things went wrong *without* any cost (no slowdown). That's because, when a problem is detected, and only when a problem is detected, we go to a 'fail' label where the current state is still known.

**Comment by lemire** [comment]
Leaving this open because I think we can do better without performance penalty.

**Comment by lemire** [comment]
I'll close this and open a distinct issue, since we have pretty detailed error types at this point.
