### ISSUE TITLE
Utf8 validation question

### ISSUE THREAD

**Issue by EgorBo** [lemire/simdjson#72]
Let's say I have a json file with `{ "name": "\udc00\ud800\uggggxy" }` content.
When I parse it using ParsedJson I get isValid == true, is it correct? 
`SIMDJSON_UTF8VALIDATE` is defined.

**Comment by lemire** [comment]
It won't be affected by `SIMDJSON_UTF8VALIDATE` since your input is ASCII.

**Comment by lemire** [comment]
But yes, I think it should fail during stage 2. If it does not, then you have found a bug.

**Comment by EgorBo** [comment]
yeah, looks more like a bug, `isValid` is true, and when I try to read that string using iterator I get `í°€â¿xy`

**Comment by lemire** [comment]
Though I did not verify it, I am flagging this as a bug. This document should blow up and we have the logic in place for it to blow up, but something goes wrong.

**Comment by geofflangdale** [comment]
I am very suspicious of the pathway through the \u handling code:

https://github.com/lemire/simdjson/blob/master/include/simdjson/jsoncharutils.h#L70-L89

I don't think it's possible that the no_check code will ever do anything but silently and undetectably generate nonsense values. I think it's possible that this code could be fixed to ensure that any invalid character use generates a codepoint with the high bit of a 32-bit integer set (e.g. by ensuring that the table is made up of int32s or is sign-extended when the bytes are shifted into place). This then means we can bail out of codepoint_to_utf8 without having to do any more checking than we do now, which is nice.

**Comment by lemire** [comment]
I have only proved it correct, not tried it.

**Comment by geofflangdale** [comment]
I believe that this is fixed now. The problem was that nothing checks the return value of that conversion to "u32" (really u16). I changed this to put 1-bits into the high 16 bits of any invalid character lookup and ensured that it's impossible to leave handle_unicode_codepoint with either the first or second codepoints invalid. 

I will add another test, as we were clearly evading the problem previously by letting stuff through that triggered the detection of the low surrogate stuff - so \uf**k for example would generate a first value > d800 and thus wind up looking for \u afterwards and fail out for that reason, not the right one.

**Comment by EgorBo** [comment]
I believe we can close this one, ported the fix to C# and verified. Thanks!
