### ISSUE TITLE
Store strings' lengths in the tape

### ISSUE THREAD

**Issue by EgorBo** [lemire/simdjson#87]
I am not sure it makes sense in the upstream but in C# I have to convert UTF8 to UTF16 so it'd be nice to have an ability to obtain string's length (currently I have to count chars till '\0' first) 
Are you interested in a PR that adds this functionality and which approach would you recommend - can I fit "string length", "offset" and `"` into the tape item? I guess I'll have to limit offset to uint32_t (as well as string length) or a separate buffer of lengths is better?

PS: I calculate the string length here https://github.com/lemire/simdjson/blob/master/include/simdjson/stringparsing.h#L119
using
```
auto length = dst - dst_start + quote_dist; // dst_start is initial dst value
```

Prototype in C#: https://github.com/EgorBo/SimdJsonSharp/commit/217d67dc8349dc6e7cd2ee81de2258b454d9919e

**Comment by lemire** [comment]
I am interested in a prototype so that we can assess it, in particular as far as performance goes. So... yeah... if you have something, then I'd be interested.

The best path forward is to try to understand the effect that this has.

We will implement it, but we must understand what it entails, and upsides and the downsides. There may be different ways to skin this cat with different tradeoffs.

cc @geofflangdale

**Comment by TkTech** [comment]
Excellent, I requested this in #40 for the exact same reason.

**Comment by EgorBo** [comment]
@TkTech oh, didn't notice that issue 🙂

**Comment by geofflangdale** [comment]
I generally like this idea. I would prefer not to add new quirky speedbumps to our implementation e.g. "we can only have 16MB strings because they wanted to pack the string offset+length+'"" code into 64 bits). 4GB strings would be fine, of course, as that's just beyond huge.

I think the ship may have already sailed on 4GB offset but similarly I wouldn't want to enforce that _just_ for this issue.

I think compressing our string tape 'way down' is not a first-class goal at this point. We are wasting tons of space by storing the same keys over and over again; if we wanted to address space, we would be far better off dealing with that (and/or optimizing for the case where we have an implicit schema and even our 'sets of keys' tend to repeat). I think putting a 4-byte size field at the start of each string is _fine_ for now.

We can stop null-terminating our strings too.

**Comment by EgorBo** [comment]
@geofflangdale makes sense, will change the PR.

**Comment by TkTech** [comment]
- [Microsoft appears to default to 4MB](https://docs.microsoft.com/en-us/dotnet/api/system.web.script.serialization.javascriptserializer.maxjsonlength?view=netframework-4.7.2).
- [IBM DataPower](https://www.ibm.com/support/knowledgecenter/en/SS9H2Y_7.6.0/com.ibm.dp.doc/json_parserlimits.html) defaults to 8K.
- All common browsers are at least 2^27
- Pretty much every other source I found used `size_t` for length prefixes.

If overhead is the primary concern, there's always schemes like https://sqlite.org/src4/doc/trunk/www/varint.wiki for varints biased towards small size strings. There are some very fast implementations.

Honestly I can't see 16MB being a problem in most cases, but if it would not add significant complexity it would be better for the prefix size to be a compile(?) time define.

**Comment by lemire** [comment]
The specification allows us to set limits on the length of strings... "An implementation may set limits on the length and character contents of strings".

Varint is branchy, so this may affect performance negatively. Think about the fact that we have many strings so the cost adds up pretty quickly.

> Honestly I can't see 16MB being a problem in most cases, but if it would not add significant complexity it would be better for the prefix size to be a compile(?) time define.

War and Peace is 2MB. However if someone encodes an image using base64, it could easily exceed 16MB. A practical solution might be to have a different type for very large strings. That's not very different from the varint idea, but instead of having branches all over, we would have a super unlikely "Super Large String" type that would never get used.

**Comment by geofflangdale** [comment]
Let's just stick a 32-bit value at the head of the string, take off the null-termination, and eat the extra 3 bytes. I'd rather do that and not have to document some limit and get another pack of people shouting at us over yet another thing.

**Comment by lemire** [comment]
Fine.  Currently we have preallocate the string tape. When we do this allocation we just have the size of the JSON. How much should we allocate?

That's the current code...
```
    size_t localstringcapacity = ROUNDUP_N(len + 32, 64);
    string_buf = new (std::nothrow) uint8_t[localstringcapacity];
```

https://github.com/lemire/simdjson/blob/a22c20fab058e740cd428ae6d6d781be765ceca5/src/parsedjson.cpp
