### ISSUE TITLE
Consider adding (runtime) AVX2 detection

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#90]
@TkTech has included a runtime AVX2 detection routine in pysimdjson: 
https://github.com/TkTech/pysimdjson/blob/develop/simdjson/cpuid.c

I am not sure what @TkTech's routine would do on ARM or POWER... so we still needs compile-time checks. Still, it would be friendlier to provide nicer errors to users having older hardware.

**Comment by TkTech** [comment]
It's extremely x86-specific. On ARM or POWER you'd just wrap the entire file in a
```
#if defined(__x86_64__) || defined(_M_AMD64)
...
#else int8_t can_use_arvx() { return 0 };
`#endif`.
```

**Comment by ioioioio** [comment]
I've pushed a branch that does runtime dispatch: [runtime_dispatch](https://github.com/lemire/simdjson/tree/runtime_dispatch). When compiled for AVX and SSE at the same time (this is what the makefiles will do by default), the function parse() (only that one) can properly select the best implementation according to the supported SIMD instruction sets. 

However, when compiled for AVX and SSE at the same time, the code produced by the compiler for the SSE functions does not work on machines using SSE. The runtime dispatch works, but the SSE implementation crashes for using some unhallowed instructions. Of course, everything still works fine when compiled specially for SSE.

Any advice would be appreciated about how to tell the compiler that some functions (and only some) should work with SSE machines.

**Comment by TkTech** [comment]
Only portable approach is to compile them both separately and then link them back into a single object.

**Comment by zbjornson** [comment]
@ioioioio try compiling without `-mXXX` flags, but adding `__attribute__ ((__target__ ("XXX")))` to your functions that use advanced extensions. That works for GCC, Clang, ICC. MSVC doesn't need an attribute. See https://godbolt.org/z/jAOsJt for an example.

**Comment by lemire** [comment]
@zbjornson

That's helpful! You are giving me back hope that we might support runtime dispatching without going blind in the process.

Here is what I think I understand...

- Visual Studio always let you use AVX intrinsics irrespective of the presence of a compile-time flag (like /arch:AVX2), but it is up to you to guard their use with a runtime CPU check. 

- If we want runtime dispatch to work under Windows, we might as well drop /arch:AVX2 compile-time flag.
- And with these function attributes, inlining is only possible if the calling function has the same attribute. Right?
- Does the compiler guard the call to these function with a runtime check? Here is what the documentation says ["At run-time, calling the function version, either directly or indirectly, will invoke the dispatcher logic which will execute the right function version."](https://gcc.gnu.org/wiki/FunctionMultiVersioning)


- It seems that instead of going with function attributes, we could have code blocks...   using [`#pragma GCC target` (GCC)](https://gcc.gnu.org/onlinedocs/gcc/Function-Specific-Option-Pragmas.html) or [the equivalent in clang](https://godbolt.org/z/u-Jm1y) Honestly, I feel like having "code blocks" would be nicer in our case. We could separate out the implementations in separate files according to separate CPU features, or at least, if we keep things in the same file, we could have distinct 'blocks' within a file... which makes it nice.

- We would need something different from the Intel compiler but I am not very concerned by that. I am not sure how many people actually use icc outside some specific areas (like HPC).

- What happens if someone compiles our code with `-mavx`? This risks breaking the dispatch, evidently, but it seems like it won't break the code...

**Comment by lemire** [comment]
Addition: 

- It is wrong or useless to test for `__AVX2__` when you are under Visual Studio. You can always use the intrinsics... What you need to do is a runtime check.

**Comment by zbjornson** [comment]
That's all in line with my understanding, yeah. (Yes to the *Addition:* as well. You probably also already noticed that MSVC has no `__SSE3__`, etc. defines -- just `__AVX__` and `__AVX2__`.)

> we might as well drop the /arch:AVX2 compile-time flag.

Yeah, if you're goal is to get one binary that works regardless of CPU features, then `/arch` should target whatever you pick as the minimum feature set.

> inlining is only possible if the calling function has the same attribute

TBH I don't know if GCC will inline in that case -- it might if you use GCC's multiversioning (see next bullet) but it would be impressive if it did so if you use your own function pointer-based dispatcher. I only do runtime dispatching for larger fns where the the overhead of a `call` is negligible. (Agner's chapter 13 talks about this a bit.)

> Does the compiler guard the call to these function with a runtime check?

Those docs you linked to are for GCC-specific multiversioning using GCC's built in runtime dispatch -- notice all the fns in their example have the same name. AFAIK Clang doesn't have this (https://reviews.llvm.org/D38596 says "abandoned"). There's no runtime check if you're just using a target attribute without GCC's multiversioning.

The more relevant docs are:
* GCC function attributes (ctrl-f for `target (options)`) https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html
* GCC function-specific pragmas https://gcc.gnu.org/onlinedocs/gcc/Function-Specific-Option-Pragmas.html
* Clang target attribute https://clang.llvm.org/docs/AttributeReference.html#target
* This SO answer for Clang `#pragma` https://stackoverflow.com/a/56395854/1218408

>  something different from the Intel compiler

I'm determined to figure this out at least out of curiosity. I think it has the best of both MSVC and GCC/Clang (pragmas and attributes, AND ability to use intrinsics regardless of `-mXXX`). I think my original godbolt works, but ATM I'm not seeing it emit `pcmpestri` ever 🤔.

> What happens if someone compiles our code with -mavx

Hmmm. I think regardless of whether you're using higher ("avx2") or lower ("sse3") function attributes, it would be fine, but I haven't though much about this. If you find something that breaks, you could use `__target__("no-avx2")` or something.

---

I have a bad habit of editing my posts to avoid GitHub sending excessive emails, hoping others will read the latest version in github. In my prior post, I edited to link to a godbolt example with `#pragma`s for GCC and Clang, https://godbolt.org/z/EA2AfA

**Comment by zbjornson** [comment]
> AFAIK Clang doesn't have this

Well now, maybe it does: https://godbolt.org/z/bp7miB

So yes: GCC, ICC, Clang, No: MSVC.

**Comment by TkTech** [comment]
Like I mentioned an approach that works everywhere on every compiler is to just compile the files separately. No need to disable optimizations like -mnative or deal with compiler specifics.

Typically (and I say typically because the single file amalgamation means you probably want to do this using ifdefs instead of different files) you compile one file (runtime dispatch initializer) with no features at all enabled. Then you compile each feature-specific file separately with the features enabled. Then you link them together. Easy.

Your runtime dispatch is called just once to initialize the library and returns a struct of pointers to the public platform-specific methods.

Use https://software.intel.com/en-us/articles/intel-software-development-emulator/ to selectively enable and disable current and future CPU features to test your variations and test that your runtime dispatch initializer is properly detecting features.

**Comment by lemire** [comment]
> Then you compile each feature-specific file separately with the features enabled. Then you link them together. Easy.

I agree that having separate builds and creating a fat binary is very attractive... as we could basically do it using our existing codebase without making it more complex.

I don't know how to do it, however. Maybe it is easy for you, but I honestly don't know how to do it. CMake handles our build setup. How do we make this work with CMake? Is there an example of an open-source project we can look at that does this? Or do you maybe have a toy example (using CMake)?

Secondly, another way I expect people are going to use our code is via the single-header release. Then we are not in charge of the build at all... How do we handle this case?

**Comment by lemire** [comment]
As a reference, torch added runtime dispatch...
https://github.com/torch/torch7/pull/852

**Comment by lemire** [comment]
@zbjornson 

What you describe 'sounds' easy, but let me narrow it down to our use case.

Currently, we have one code base, and various small functions that are specialized. Importantly, these specialized functions must be inlined since they are called often. They are small. We can't do runtime checks at their level.

To make things nice and modular, we use templates and template specialization. This makes the code manageable and nice. 

E.g., it looks like this except that the functions call other functions... so it is more complicated...

```C++
template <class cpufeature>
void generic_function() {
  auto z = do_first_part<cpufeature>(); // this needs fancy instructions
  // do some work on z...
  ... // generic code omitted
 do_second_part<cpufeature>(z); // this needs fancy instructions
}
```

My gut feeling at this time is that to make your approach work, we will need to drop the template and replace them with C macros, which will be a shame from a software engineering point of view.

Do you have a better idea maybe?

To illustrate the issue, let me show you some code...

https://godbolt.org/z/OQbf64

**Comment by zbjornson** [comment]
I know these all need to be inlinable, but just for the sake of showing something that works with (32-bit, 64-bit) x (Clang, GCC, MSVC, ICC) x (x86, ARM) and function templates, I took your [`compute_quote_mask`](https://github.com/lemire/simdjson/blob/master/include/simdjson/stage1_find_marks.h) function and made a version with runtime function pointer-based dispatching. This came out easy to read (almost no preprocessor directives).

* C++11 version using `[[gnu::target(T)]]`  https://godbolt.org/z/z_CuEh. Note that *all* feature requirements must be part of the template parameters and not preprocessor directives, e.g. the combo of sse4.2 and pclmulqdq that you currently have as PPDs. If you don't want to enumerate all combos, I think you can exchange the type safety of the `instruction_set` `enum class` with the ability to OR features together and use a plain `enum`: https://godbolt.org/z/vuahvb
* Version supporting pre-C++11 https://godbolt.org/z/pl0Uu3

(There are a bunch of compiler tabs sort of hidden. Use the drop-down menu in the top-right, next to "maximise" and "close" to see them all.)

Okay, but since you need inlining, you'd have to do that all the way up the call stack. Started doing that here (https://github.com/lemire/simdjson/compare/master...zbjornson:zb/attempt-1) and got relatively far (see also notes below) but since GCC doesn't apply a function's `target` attribute to other functions that it calls, inlining fails once you start getting to the higher-level functions (e.g. `cmp_mask_against_input<T>` into `find_odd_backslash_sequences`). Using vector types in a struct is also a tricky, I think I got GCC working but not Clang. I've thought of a few ways around both of these so far but none are elegant or quick, so I stopped for now.

I didn't know how this project was structured until now. Function targeting is nice when you have hot functions that don't need to be inlined, but linking multiple versions together is definitely a good option for this scenario. A downside is a potentially bigger output, but I don't know if that matters here. There might be some major refactoring that would make function targeting work cleanly.

Other notes:

* That branch has a version of simddetection.h from @ioioioio 's branch with some modifications. Notably, all `SIMDExtensions` enum values are unique across all architectures so more preprocessor directives could be eliminated.
* @ioioioio your runtime dispatch enables SSE4.2 based on the presence of SSE2. I added a true SSE4.2 check in my branch. That could be a source of crashes depending on what you were testing on.
* `simdjson.h` defines `avx2`, `sse4_2` and `neon`, but you have preprocessor directives for PCLMUL and ARM crypto, for example, and a lot of functions marked sse4.2 only actually need sse2. Especially since AVX512 introduces more combinations of feature sets and I see comments hinting that you might add AVX512__ stuff in the future, you'd need to decide what granularity you want to specialize at.

Sorry that didn't turn out more useful (or maybe you, being familiar with this code, see some refactoring that works around needing to inline at this level).

---

You asked *What happens if someone compiles our code with -mavx* -- two of the godbolt tabs show `-march=core2` and `-march=skylake-avx512`. The only change I see is that `skylake-avx512` uses VEX-encoding. Compiling with `-mno-avx2` (which would be a direct conflict with the "avx2" specialization) works as well. (I hope the compilers will do this, but need to check that `VZEROUPPER` is emitted where needed given that the avx2 specializations are VEX-encoded.)

---

On ICC: [The `target` attribute only applies to MIC](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-target), so it has to be handled the same way as MSVC (all intrinsics are always allowed regardless of `-m` flags, coder-beware).

**Comment by lemire** [comment]
@zbjornson

Amazing work. We’ll try to take it further.

**Comment by lemire** [comment]
PHP has runtime dispatch.

https://github.com/php/php-src/blob/6e630fe79b734c0923d8dc0a7b622983e68dad58/ext/standard/base64.c#L431

**Comment by lemire** [comment]
White board work on this issue :

![IMG_0357](https://user-images.githubusercontent.com/391987/61412697-8b3ca600-a8b7-11e9-819d-2fd9d0c939f4.jpeg)

**Comment by jkeiser** [comment]
Have you considered using the [libsimdpp](https://github.com/p12tic/libsimdpp) approach?

I was actually looking at using it in simdjson to support more architectures and move some of the platform-specific stuff to a more supported library.

**Comment by ioioioio** [comment]
If I understand correctly, I think we have considered something similar (the "link A+B+C" on the white board), and our experiments showed it would probably work. The problem is that we want to offer a single header file to the user, which would not be possible with that approach.

If you're curious, I pushed a [new branch](https://github.com/lemire/simdjson/tree/runtime_dispatch2) on which everything compile fine with gcc. However, the tests show there is something wrong with clang. Hopefully it will be merged soon.

**Comment by lemire** [comment]
@jkeiser

How would you handle the fact that for efficiency, we need different algorithms depending on the ISA? 

The problem we face is not that it is hard to write NEON or AVX-512 code... but that, as @ioioioio points out, we want zero-overhead runtime dispatch based on CPU features without having to assume that the user relies on, say, CMake.

It works now and it is clean... but some typo somewhere is blocking builds with clang.

**Comment by jkeiser** [comment]
@lemire I haven't seen the branch yet, and I wasn't knocking it :) I was just looking at the lib and noticed the dispatch mechanism. It would detect more architectures, and maybe even enable partial support for them without tons of work (imagine a "generic simd" version of the algorithm that works on wide instructions where possible, and then #ifs into specifics when an architecture has something better than the generics can provide). From my impression of it, their dispatch method isn't a per-instruction dispatch, it lets you compile a separate version for each architecture, #ifs and all.


The main reason *I* was thinking about using a library was making bootstrapping and comprehension easier. A lot of the instructions we use *do* have generic analogues in that library, and excluding the _mm's and using operator overloading makes the algorithm flow easier to read. You save the deep stuff for the moments where what you're doing really is unique, like with clmul. This really hit home for me when writing the different versions of &, \, ^ and ~ for SSE4.2 and AVX when trying to widen the bitmasks.

**Comment by lemire** [comment]
@jkeiser 

>  It looks like it lets you generate a version of your function for all architectures automatically, and then selects the platform-specific version at runtime.

As pointed out by @ioioioio, it does so with multiple compile passes. That's something we considered but it does not work with a single-header library that you can just plug into your project. You have to configure your build system. We are currently going with something proposed by @zbjornson that should allow us to have a single-header library.  It is harder to do because the dispatching logic has to be in the C++ but I think that once it is done, it is going to be more powerful. And it is not going to worsen our code base.

> I'd love to end up with a library one way or the other that forms the basis for a JSON parser, but that I can also use as a basis for SIMD parsing of CSV and XML. I'm excited to see where this develops.

We share similar objectives. See https://github.com/geofflangdale/simdcsv

> I think you still #if depending on architecture. 
> then #ifs into specifics when an architecture has something better than the generics can provide).

If you are going to mix something like libsimdpp with intrinsics or asm, I submit to you that you are not in great shape.

I am familiar with  libsimdpp. It is great work... if you are going to pick a SIMD API, it is the one to pick. But...

See my experiments with it...

https://github.com/lemire/multiplatform_simd_recipes/

Basically, in every single instances I tried, using libsimdpp came with a performance penalty on at least one platform, sometimes very significantly. And you are restricted in the set of operations that you can support.

Look at the NEON vs. AVX code in simdjson... there is just not a whole lot of generic content there... Maybe it looks superficially similar, but once you take away the scalar code, there is a lot of specialization per ISA.



> my inclination towards a library is mainly for comprehension

If that's a primary goal, then I would recommend against using SIMD functions. One can rely on autovectorization.

My view is that if you are going to go through the trouble of manually vectorizing your code...  you must be able to specialize the code to the ISA. You must also have access to all instructions of the ISA.

For something like simdjson, the intrinsics are probably the least of your worries. That is, it is not because we use intrinsics that it is hard. Yes, it is not very accessible, but even if you could replace the +, -, xor with symbols, it would still be tricky. Operator overloading only gets you so far.

And how confident are you that you are going to be able to reason about the performance once you have abstracted away the instruction you are using?

That's not to say that you don't have a good point. I am acutely aware that SIMD instructions are not very accessible. There are solutions. Using something like libsimdpp can certainly be part of the solution, and it can work well in some cases... but I think that the problem, in general, is more complicated.

**Comment by jkeiser** [comment]
I'm quite sure you're right about all that, and this is definitely an area where performance compromise is unwarranted--parsing libraries like this are in the critical path for a huge percentage of all communications on the internet. Thanks for sharing your enlightenment :)

**Comment by lemire** [comment]
We have a working PR now...
https://github.com/lemire/simdjson/pull/230

It is based on @ioioioio work, and benefited from @jkeiser fixes for VS.

**Comment by lemire** [comment]
This has been merged. It was a lot of work, but we have something that works. 

@jkeiser rightfully objects to our use of macros, but I think that's a distinct issue. Closing.

**Comment by lemire** [comment]
The current design would not have been possible without @zbjornson so created was added.

**Comment by zbjornson** [comment]
Happy to help, glad you figured something out. Sorry I didn't get to review your PR, I've been on (and am still on) vacation for the last week (and next week).

**Comment by lemire** [comment]
@zbjornson It was incredibly difficult to make your approach work even though it is sound.

The most frustrating difficulty is that clang attribute does not work with C++ namespaces, and that's not documented anywhere (possibly a bug). For the longest time, all we got were random error messages.

But now that it works, it is a really good framework.

@ioioioio  did most of the software engineering... and I think that the nice design will pay out.
